include: package:lint/analysis_options.yaml

analyzer:
  errors:
    # treat missing required parameters as an error (not a hint or warning)
    missing_required_param: error
    parameter_assignments: error
    # treat missing returns as a error (not a hint or warning)
    missing_return: error
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    # ------ Disable individual rules ----- #
    #                 ---                   #
    # Turn off what you don't like.         #
    # ------------------------------------- #

    # Util classes are awesome!
    avoid_classes_with_only_static_members: false


    # ------ Enable individual rules ------ #
    #                 ---                   #
    # These rules here are good but too     #
    # opinionated to enable them by default #
    # ------------------------------------- #

    # Make constructors the first thing in every class
    sort_constructors_first: true
